#!/usr/bin/env python3

import time
import onetimepass as otp
import sys
import os.path

def die (msg):
    print(msg)
    exit(1)

if (len(sys.argv) != 2):
    die("Usage: %s <secret-file>" % sys.argv[0])

if (os.path.isfile(sys.argv[1]) == False):
    die("File %s does not exist" % sys.argv[1])

with open(sys.argv[1], 'r') as f:
    secret = f.readline().rstrip()
    f.close()

tsecs  = int(time.time())
window = 2
for step in range (-window,window+1):
    deltat = 30 * step
    token  = otp.get_totp(secret, clock=(tsecs + deltat))
    print ("OTP (t = %7s %06d" % ("0):>>" if deltat == 0 else "%+3d):  " % deltat, token))
